# Luna UI configuration file.

indices:
  const_ntsb:
    data_schema:
      text_representation:
        type: str
        samples:
          - Can be assumed to have all other details
      properties.entity.dateTime:
        type: str
        samples:
          - "2023-01-12T11:00:00"
          - "2023-01-11T18:09:00"
          - "2023-01-10T16:43:00"
          - "2023-01-28T19:02:00"
          - "2023-01-12T13:00:00"
      properties.entity.dateAndTime:
        type: str
        samples:
          - "January 28, 2023 19:02:00"
          - "January 10, 2023 16:43:00"
          - "January 11, 2023 18:09:00"
          - "January 12, 2023 13:00:00"
          - "January 12, 2023 11:00:00"
      properties.entity.lowestCeiling:
        type: str
        samples:
          - "Broken 3800 ft AGL"
          - "Broken 6500 ft AGL"
          - "Overcast 500 ft AGL"
          - "Overcast 1800 ft AGL"
      properties.entity.aircraftDamage:
        type: str
        samples:
          - "Substantial"
          - "None"
          - "Destroyed"
      properties.entity.conditions:
        type: str
        samples:
          - "Instrument (IMC)"
          - "IMC"
          - "VMC"
          - "Visual (VMC)"
      properties.entity.departureAirport:
        type: str
        samples:
          - "Somerville, Tennessee"
          - "Colorado Springs, Colorado (FLY)"
          - "Yelm; Washington"
          - "Winchester, Virginia (OKV)"
          - "San Diego, California (KMYF)"
      properties.entity.accidentNumber:
        type: str
        samples:
          - "CEN23FA095"
          - "ERA2BLAT1I"
          - "WPR23LA088"
          - "ERA23FA108"
          - "WPR23LA089"
      properties.entity.windSpeed:
        type: str
        samples:
          - "10 knots"
          - "7 knots"
          - "knots"
          - "19 knots gusting to 22 knots"
      properties.entity.day:
        type: str
        samples:
          - "2023-01-12"
          - "2023-01-10"
          - "2023-01-20"
          - "2023-01-11"
          - "2023-01-28"
      properties.entity.destinationAirport:
        type: str
        samples:
          - "Somerville, Tennessee"
          - "Yelm; Washington"
          - "Agua Caliente Springs, California"
          - "Liberal, Kansas (LBL)"
          - "Alabaster, Alabama (EET)"
      properties.entity.location:
        type: str
        samples:
          - "Hooker, Oklahoma"
          - "Somerville, Tennessee"
          - "Yelm; Washington"
          - "Agua Caliente Springs, California"
          - "Dayton, Virginia"
      properties.entity.operator:
        type: str
        samples:
          - "On file"
          - "First Team Pilot Training LLC"
          - "file On"
          - "Anderson Aviation LLC"
          - "Flying W Ranch"
      properties.entity.temperature:
        type: str
        samples:
          - "18'C /-2'C"
          - "15.8C"
          - "13'C"
          - "2C / -3C"
      properties.entity.visibility:
        type: str
        samples:
          - "miles"
          - "0.5 miles"
          - "7 miles"
          - "10 miles"
      properties.entity.aircraft:
        type: str
        samples:
          - "Piper PA-32R-301"
          - "Beech 95-C55"
          - "Cessna 172"
          - "Piper PA-28-160"
          - "Cessna 180K"
      properties.entity.conditionOfLight:
        type: str
        samples:
          - "Night/dark"
          - "Night"
          - "Day"
          - "Dusk"
      properties.entity.windDirection:
        type: str
        samples:
          - "190°"
          - "200"
          - "2005"
          - "040°"
      properties.entity.lowestCloudCondition:
        type: str
        samples:
          - "Broken 3800 ft AGL"
          - "Overcast 500 ft AGL"
          - "Clear"
          - "Overcast 200 ft AGL"
      properties.entity.injuries:
        type: str
        samples:
          - "Minor"
          - "Fatal"
          - "None"
          - "3 None"
          - "2 None"
      properties.entity.flightConductedUnder:
        type: str
        samples:
          - "Part 91: General aviation Instructional"
          - "Part 135: Air taxi & commuter Non-scheduled"
          - "Part 91: General aviation Personal"
          - "Part 135: Air taxi & commuter Scheduled"
          - "Part 91: General aviation Business"
    examples:
      - query: "List the incidents in Georgia in 2023."
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports
              index: const_ntsb
              node_id: 0
              query:
                bool:
                  must:
                    - range:
                        properties.entity.dateTime:
                          gte: 2023-01-01T00:00:00
                          lte: 2023-12-31T23:59:59
                          format: strict_date_optional_time
                    - match:
                        properties.entity.location: Georgia

      - query: "Show the incidents involving Piper aircraft."
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports
              node_id: 0
              index: const_ntsb
              query:
                match:
                  properties.entity.aircraft: "Piper"

      - query: "How many incidents happened in clear weather?"
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports in clear weather
              index: const_ntsb
              node_id: 0
              query:
                match:
                  properties.entity.conditions: "VMC"
            - operator_name: Count
              description: Count the number of incidents
              node_id: 1
              distinct_field: properties.entity.accidentNumber
              input:
                - 0

      - query: "What types of aircrafts were involved in accidents in California?"
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports in California
              node_id: 0
              index: const_ntsb
              query:
                match:
                  properties.entity.location: "California"
            - operator_name: TopK
              description: Get the types of aircraft involved in incidents in California
              node_id: 1
              field: properties.entity.aircraft
              primary_field: properties.entity.accidentNumber
              K: 100
              descending: false
              llm_cluster: false
              llm_cluster_instruction: null
              input:
                - 0

      - query: "Which aircraft accidents in California in 2023 occurred when the wind was stronger than 4 knots?"
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports in California in 2023
              node_id: 0
              index: const_ntsb
              query:
                bool:
                  must:
                    - range:
                        properties.entity.dateTime:
                          gte: "2023-01-01T00:00:00"
                          lte: "2023-12-31T23:59:59"
                          format: strict_date_optional_time
                    - match:
                        properties.entity.location: "California"
            - operator_name: LlmFilter
              description: Filter to reports with wind speed greater than 4 knots
              node_id: 1
              index: OPENSEARCH_INDEX
              question: "Is the wind speed greater than 4 knots?"
              field: properties.entity.windSpeed
              input:
                - 0

      - query: "Which three aircraft types were involved in the most accidents?"
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports
              node_id: 0
              index: const_ntsb
              query:
                match_all: {}
            - operator_name: TopK
              description: Get the top three aircraft types involved in accidents
              node_id: 1
              field: properties.entity.aircraft
              primary_field: properties.entity.accidentNumber
              K: 3
              descending: true
              llm_cluster: false
              llm_cluster_instruction: null
              input:
                - 0
      - query: "Show some incidents where pilot training was mentioned as a cause"
        plan:
          nodes:
            - operator_name: QueryVectorDatabase
              description: Get incident reports mentioning pilot training
              node_id: 0
              index: OPENSEARCH_INDEX
              query_phrase: "pilot training"

      - query: "Show all incidents involving a Cessna 172 aircraft"
        plan:
          nodes:
            - operator_name: QueryDatabase
              description: Get all the incident reports involving a Cessna 172 aircraft
              node_id: 0
              index: OPENSEARCH_INDEX
              query:
                match:
                  properties.entity.aircraft: "Cessna 172"
